### ISSUE TITLE
Hanging punctuation not supported

### ISSUE THREAD

**Issue by MrXCQ** [matori/unformedbuilding.com#55]
Hi,do you know how to use Hanging punctuation  CSS3 in google Chrome？
Thanks！

**Comment by matori** [comment]
@MrXCQ Ah, Sorry, I have no idea how to use hanging-punctuation on Google Chrome.
It seems does not support yet, and has no action.
ref https://bugs.chromium.org/p/chromium/issues/list?q=css%20hanging%20punctuation
